name: Send POST Request on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  send-post-request:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo code
        uses: actions/checkout@v4

      - name: Check if PR is merged
        id: check-merge
        run: |
          if [ "${{ github.event.pull_request.merged }}" == "true" ]; then
            echo "MERGED=true" >> $GITHUB_ENV
          else
            echo "MERGED=false" >> $GITHUB_ENV
          fi

      - name: Get commit and repo details
        if: env.MERGED == 'true'
        id: get-details
        run: |
          # Fetch the repository ID
          REPO_ID=${{ github.event.repository.id }}

          # Other commit and PR details
          MERGE_COMMIT_SHA=${{ github.event.pull_request.merge_commit_sha }}

          # Fetch commit message this way
          COMMIT_MESSAGE=$(git show -s --format=%B "$MERGE_COMMIT_SHA" | tr '\n' ' ')

          TIMESTAMP=$(git show -s --format=%ci "$MERGE_COMMIT_SHA")
          PR_TITLE=${{ github.event.pull_request.title }}
          PR_AUTHOR=${{ github.event.pull_request.user.login }}
          PR_LINK=${{ github.event.pull_request.html_url }}
          REPO_NAME=${{ github.repository }}

          echo "REPO_ID=$REPO_ID" >> $GITHUB_ENV
          echo "COMMIT_HASH=$MERGE_COMMIT_SHA" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV
          echo "PR_AUTHOR=$PR_AUTHOR" >> $GITHUB_ENV
          echo "PR_LINK=$PR_LINK" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      - name: Send POST request to backend
        if: env.MERGED == 'true'
        env:
          BACKEND_URL: ${{ secrets.BACKEND_COMMIT }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: |
          curl -X POST "$BACKEND_URL" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $AUTH_TOKEN" \
          -d '{
            "repository_id": "'"${{ env.REPO_ID }}"'",
            "commit_timestamp": "'"${{ env.TIMESTAMP }}"'",
            "commit_hash": "'"${{ env.COMMIT_HASH }}"'",
            "commit_message": "'"${{ env.COMMIT_MESSAGE }}"'",
            "pr_title": "'"${{ env.PR_TITLE }}"'",
            "pr_author": "'"${{ env.PR_AUTHOR }}"'",
            "pr_link": "'"${{ env.PR_LINK }}"'",
            "repository_name": "'"${{ env.REPO_NAME }}"'"
          }'
