name: Send POST Request on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  send-post-request:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo code
        uses: actions/checkout@v4

      - name: Check if PR is merged
        id: check-merge
        run: |
          if [ "${{ github.event.pull_request.merged }}" == "true" ]; then
            echo "MERGED=true" >> $GITHUB_ENV
          else
            echo "MERGED=false" >> $GITHUB_ENV
          fi

      - name: Get commit details
        if: env.MERGED == 'true'
        id: get-commit-details
        run: |
          # Get the merge commit hash
          MERGE_COMMIT_SHA=${{ github.event.pull_request.merge_commit_sha }}

          # Get the commit message
          COMMIT_MESSAGE=$(git show -s --format=%B $MERGE_COMMIT_SHA | tr '\n' ' ')

          # Get the local commit timestamp in ISO 8601 format
          TIMESTAMP=$(git show -s --format=%ci $MERGE_COMMIT_SHA)

          echo "COMMIT_HASH=$MERGE_COMMIT_SHA" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      - name: Send POST request to backend
        if: env.MERGED == 'true'
        run: |
          BACKEND_URL="http://195.35.11.190:9093/add-action" 

          curl -X POST $BACKEND_URL \
          -H "Content-Type: application/json" \
          -d '{
            "commit_timestamp": "'"${{ env.TIMESTAMP }}"'",
            "commit_hash": "'"${{ env.COMMIT_HASH }}"'",
            "commit_message": "'"${{ env.COMMIT_MESSAGE }}"'"
          }'
